### ISSUE TITLE
All of the .md hyperlinks are broken

### ISSUE THREAD

**Issue by hydrosquall** [cytoscape/cytoscape-manual#41] opened 2019-01-19 03:31 UTC
Hi, thanks for the great work on this project! I wanted to flag an issue that I noticed when browsing the docs today.

The issue is that all the links to `.md` files work on on Github, but break when the page is rendered to html.

For example, click on  `Groups` on this page in the text `Most often, Groups are more functional and easier to use.` 

http://manual.cytoscape.org/en/stable/Nested_Networks.html

A fix could be to either update all the links from .md to HTML, or to update the script which turns the markdown files into HTML to transform all the markdown links into HTML ones.

**Comment by hydrosquall** [comment] 2019-01-24 18:26
A coworker suggested looking into using this library in the Sphinx config to help with converting the URLs correctly in a non-manual way: 

https://github.com/rtfd/recommonmark

**Comment by ritwikagarwal** [comment] 2019-05-19 11:20
I think the issue is fixed now as I can easily render all the links on html currently and correctly.
Thanks.

**Comment by hydrosquall** [comment] 2019-05-19 16:19
It looks like this was done through the good work of @khanspers - thank you :)! 

(Via commits like this: https://github.com/cytoscape/cytoscape-manual/commit/29c4cef647c81019ca36015856872014ac0f3d4f )

I think it could still be worthwhile to see about automating this in the build step to avoid similar manual work in the future, but I'll leave it to the project maintainers to decide if this issue should be left open.

**Closed as completed** 2019-05-23 15:32 UTC

**Comment by joshtburdick** [comment] 2024-01-10 16:04
This seems to have recurred, at least when I click on
[https://manual.cytoscape.org/en/stable/Nested_Networks.html
](https://manual.cytoscape.org/en/stable/Nested_Networks.html
)

I'm using Chrome, on Mac OS X.

(I haven't used Cytoscape much, but the documentation otherwise looks well-done.)
